flows:
  default:
    - log: "Hello!"
  onPush:
    - log: "On branch: ${event.commitId}"

triggers:
  - github:
      version: 1
      entryPoint: onPush
      useEventCommitId: true
      type: "push"
      branch: ".*"
