flows:
  default:
    - log: "Hello!"
  onPush:
    - log: "We got: ${event.payload.after}"

triggers:
  - github:
      version: 2
      entryPoint: onPush
      useEventCommitId: true
      conditions:
        type: "push"
        branch: ".*"
